[env:cardputer]
platform = espressif32@^6.5.0
board = m5stack-stamps3
framework = arduino

lib_deps =
    https://github.com/m5stack/M5Cardputer.git
    bblanchon/ArduinoJson@^7.1.0
    mikalhart/TinyGPSPlus@^1.1.0

board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 1500000

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -std=gnu++17
    -DARDUINO_LOOP_STACK_SIZE=32768

build_unflags = -std=gnu++11
